sample_repos:
  - repo_url: "https://github.com/user/repo1"
    stars: 23
  - repo_url: "https://github.com/user/repo2"
    stars: 17

api:
  use_auth: false
  token_env_var: "GITHUB_TOKEN"
  max_retries: 3
  request_delay_seconds: 1.0

download:
  clone_depth: 1
  temp_dir: "data/tmp/"
